### PR TITLE
Build uhd_test library as static when `-DBUILD_SHARED_LIBS=ON`

### PR DESCRIPTION
**Pull request by SoapGentoo**
# Pull Request Details

## Description

`uhd_test.so` lacks the necessary symbols for testing due to default visibility set to hidden when `-DBUILD_SHARED_LIBS=ON`. The proper fix is to always build `uhd_test.a` only.

## Related Issue

not that I'm aware of

## Which devices/areas does this affect?

only CMake

## Testing Done

Tested with `-DBUILD_SHARED_LIBS=ON` (which is the default on Gentoo)

## Checklist

- [x] I have read the CONTRIBUTING document.
- [x] My code follows the code style of this project. See CODING.md.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes, and all previous tests pass.
- [ ] I have checked all compat numbers if they need updating (FPGA compat,
      MPM compat, noc_shell, specific RFNoC block, ...)

### CODE REVIEW

**Comment by SoapGentoo** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by SoapGentoo** [comment]
recheck

**Comment by michaelld** [comment]
@SoapGentoo without this change, what is the output of running this test? A before-and-after set of outputs would be useful here. Thx!

**Comment by SoapGentoo** [comment]
@michaelld linking for the tests fails:
```
[516/702] : && /usr/bin/x86_64-pc-linux-gnu-g++ -Os -march=native -mtune=native -pipe -frecord-gcc-switches -fvisibility=hidden -fvisibility-inlines-hidden -Wl,-O1 -Wl,--as-needed -Wl,--defsym=__gentoo_check_ldflags__=0 tests/CMakeFiles/sph_recv_test.dir/sph_recv_test.cpp.o -o tests/sph_recv_test -L/var/tmp/portage/net-wireless/uhd-4.1.0.4/work/uhd-4.1.0.4/host/tests/common -Wl,-rpath,/usr/lib64  lib/libuhd.so.4.1.0  tests/common/libuhd_test.so  /usr/lib64/libboost_chrono.so.1.77.0  /usr/lib64/libboost_date_time.so.1.77.0  /usr/lib64/libboost_filesystem.so.1.77.0  /usr/lib64/libboost_program_options.so.1.77.0  /usr/lib64/libboost_serialization.so.1.77.0  /usr/lib64/libboost_thread.so.1.77.0  /usr/lib64/libboost_unit_test_framework.so.1.77.0  /usr/lib64/libboost_system.so.1.77.0  /usr/lib64/libboost_atomic.so.1.77.0  -lpthread  -lpthread  -ldl  -lusb-1.0  lib/rc/libuhd-resources.a  /usr/lib64/libpython3.9.so && :
FAILED: tests/sph_recv_test 
: && /usr/bin/x86_64-pc-linux-gnu-g++ -Os -march=native -mtune=native -pipe -frecord-gcc-switches -fvisibility=hidden -fvisibility-inlines-hidden -Wl,-O1 -Wl,--as-needed -Wl,--defsym=__gentoo_check_ldflags__=0 tests/CMakeFiles/sph_recv_test.dir/sph_recv_test.cpp.o -o tests/sph_recv_test -L/var/tmp/portage/net-wireless/uhd-4.1.0.4/work/uhd-4.1.0.4/host/tests/common -Wl,-rpath,/usr/lib64  lib/libuhd.so.4.1.0  tests/common/libuhd_test.so  /usr/lib64/libboost_chrono.so.1.77.0  /usr/lib64/libboost_date_time.so.1.77.0  /usr/lib64/libboost_filesystem.so.1.77.0  /usr/lib64/libboost_program_options.so.1.77.0  /usr/lib64/libboost_serialization.so.1.77.0  /usr/lib64/libboost_thread.so.1.77.0  /usr/lib64/libboost_unit_test_framework.so.1.77.0  /usr/lib64/libboost_system.so.1.77.0  /usr/lib64/libboost_atomic.so.1.77.0  -lpthread  -lpthread  -ldl  -lusb-1.0  lib/rc/libuhd-resources.a  /usr/lib64/libpython3.9.so && :
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: tests/CMakeFiles/sph_recv_test.dir/sph_recv_test.cpp.o: warning: relocation against `_ZTV14mock_zero_copy' in read-only section `.text._ZN14mock_zero_copyD2Ev[_ZN14mock_zero_copyD5Ev]'
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: tests/CMakeFiles/sph_recv_test.dir/sph_recv_test.cpp.o: in function `test_sph_recv_one_channel_normal::test_method()':
sph_recv_test.cpp:(.text+0x11737): undefined reference to `mock_zero_copy::mock_zero_copy(uhd::transport::vrt::if_packet_info_t::link_type_t, unsigned long, unsigned long)'
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: tests/CMakeFiles/sph_recv_test.dir/sph_recv_test.cpp.o: in function `test_sph_recv_one_channel_sequence_error::test_method()':
sph_recv_test.cpp:(.text+0x14cb7): undefined reference to `mock_zero_copy::mock_zero_copy(uhd::transport::vrt::if_packet_info_t::link_type_t, unsigned long, unsigned long)'
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: tests/CMakeFiles/sph_recv_test.dir/sph_recv_test.cpp.o: in function `test_sph_recv_one_channel_inline_message::test_method()':
sph_recv_test.cpp:(.text+0x18568): undefined reference to `mock_zero_copy::mock_zero_copy(uhd::transport::vrt::if_packet_info_t::link_type_t, unsigned long, unsigned long)'
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: tests/CMakeFiles/sph_recv_test.dir/sph_recv_test.cpp.o: in function `std::shared_ptr<mock_zero_copy> std::make_shared<mock_zero_copy, uhd::transport::vrt::if_packet_info_t::link_type_t>(uhd::transport::vrt::if_packet_info_t::link_type_t&&)':
sph_recv_test.cpp:(.text._ZSt11make_sharedI14mock_zero_copyJN3uhd9transport3vrt16if_packet_info_t11link_type_tEEESt10shared_ptrIT_EDpOT0_[_ZSt11make_sharedI14mock_zero_copyJN3uhd9transport3vrt16if_packet_info_t11link_type_tEEESt10shared_ptrIT_EDpOT0_]+0x70): undefined reference to `mock_zero_copy::mock_zero_copy(uhd::transport::vrt::if_packet_info_t::link_type_t, unsigned long, unsigned long)'
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: tests/CMakeFiles/sph_recv_test.dir/sph_recv_test.cpp.o: in function `mock_zero_copy::~mock_zero_copy()':
sph_recv_test.cpp:(.text._ZN14mock_zero_copyD2Ev[_ZN14mock_zero_copyD5Ev]+0x3): undefined reference to `vtable for mock_zero_copy'
/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: warning: creating DT_TEXTREL in a PIE
collect2: error: ld returned 1 exit status
```
due to the fact that `tests/common/libuhd_test.so` has all of its symbols hidden. `-fvisibility=hidden` only affects shared libraries, not static archives.

**Comment by michaelld** [comment]
@SoapGentoo Thanks for that info. How are you configuring cmake & what is the OS you're building on? We do a ton of builds with tests enabled and I don't we've come across this issue before. I think the fix makes sense, but we need to verify it.

**Comment by SoapGentoo** [comment]
@michaelld try and build uhd on any Linux distro with `cmake -DBUILD_SHARED_LIBS=ON`. You can try it in a Gentoo VM, but it should fail just as well on Debian/Ubuntu (with `-DBUILD_SHARED_LIBS=ON`).

**Comment by SoapGentoo** [comment]
The problem is the following:

| `add_library()` call | implications |
| ------------- | ------------- |
| `add_library(uhd_test STATIC SOURCES)` | build static `libuhd_test.a` from `SOURCES` |
| `add_library(uhd_test SHARED SOURCES)` | build shared `libuhd_test.so` from `SOURCES` |
| `add_library(uhd_test SOURCES)` | build either `libuhd_test.a` or `libuhd_test.so` from `SOURCES`, depending on the value of [`BUILD_SHARED_LIBS`](https://cmake.org/cmake/help/v3.23/variable/BUILD_SHARED_LIBS.html). If this variable is not defined, build a static `libuhd_test.a` |

By not explicitly building a purely static archive (even though implied 3 lines above in the source), tests break in the presence of `-DBUILD_SHARED_LIBS=ON`, due to the fact that `-fvisibility=hidden` hides all symbols in `libuhd_test.so`, which doesn't happen when building a static archive `libuhd_test.a`.

**Comment by michaelld** [comment]
@SoapGentoo great explanation. Tried this this morning & verified what you wrote. LGTM. We will create an internal PR for this change & tag this public PR in it. Should go through pretty quickly I hope given how simple it is. We'll see.

**Pull request closed without merging**
