### PR TITLE
cmake: Remove warnings for CMake >= 3.17 version.

### PR DESCRIPTION
**Pull request by drmpeg**
Signed-off-by: Ron Economos <w6rz@comcast.net>

## Description
Removes "find_package_handle_standard_args" warnings.

## Which devices/areas does this affect?
Build of UHD and other builds that use UHD (GNU Radio)

## Testing Done
Built UHD and GNU Radio on Ubuntu 18.04.

## Checklist

- [x] I have read the CONTRIBUTING document.
- [x] My code follows the code style of this project. See CODING.md.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

**Comment by dkozel** [comment]
Hi @atrnati and @michael-west. Could this PR get looked at please? We're seeing it on GNU Radio CI builds.

**Review by atrnati — APPROVED** [review]
Looks good to me.

**Comment by michaelld** [comment]
The changes for the `REQUIRED` variable are solid (though not complete, and `unset` is preferred). There's a better way to do the `PkgConfig` stuff that CMake uses internally & we should be using ... `find_package(PkgConfig QUIET)` instead of `include(FindPkgConfig)` ... since the latter will check the status of `FOUND_PKGCONFIG` and if `TRUE` then the subsequent call to effectively the latter will _not_ be issued. I've verified that this change works cleanly with CMake 3.20; this is a much cleaner solution than from in this PR. I will deal with this PR internally. Thanks for your work @drmpeg !

**Comment by drmpeg** [comment]
Not fixed in 4.1.0.0 :(

**Pull request closed without merging**
