### PR TITLE
Static boost build

### PR DESCRIPTION
**Pull request by jsc-paneda**
We have had some issues with conflicting boost versions when installing the uhd driver. So I added a -DBOOST_STATIC=on option that builds and link the boost deps. static. This makes the uhd driver independent of any boost version installed on the target.
If there's an interest to merge this, I'll add an instruction of the needed prerequisites.

### CODE REVIEW

**Comment by mbr0wn** [comment]
Interesting -- I'll take a look at this in the coming days. We may have to modify this a bit. The option might be useful for UHD users, though.

**Comment by mbr0wn** [comment]
Interesting -- I'll take a look at this in the coming days. We may have to modify this a bit. The option might be useful for UHD users, though.

**Comment by jsc-paneda** [comment]
OK nice. To try it, the prerequisites are:
1.Download desired version of boost from www.boost.org and extract to any directory, e.g. /home/user/thirdpart/boost/
2. A one-time build of the tool b2/bjam is also needed. Run bootstrap within the BOOST_ROOT-folder.
3. Configure the BOOST_ROOT environment variable to point to the root folder of the Boost file tree.
4. Build with the -DCMAKE_STATIC_BOOST=on (the build process will only build the boost libs needed by uhd so its rather quick).

**Comment by mbr0wn** [comment]
We decided to not move forward on this. There seems to be little demand; and it's something that we need to add a continuous testing framework for.

**Pull request closed without merging**
