### PR TITLE
Fix DBSRX support on USRP1

### PR DESCRIPTION
**Pull request by Aang23**
# Pull Request Details

This fixes the DBSRX daughterboard not being initialized properly on older USRPs.

## Description

An USRP1 with the first generation DBSRX would not work on newer libuhd versions, despite working just fine on an older system.

## Related Issue

https://github.com/EttusResearch/uhd/issues/394

## Which devices/areas does this affect?

Not really sure, probably only the USRP1

## Testing Done

Tested in the setup stated above, resulting the DBSRX board working as expected.

## Checklist

- [X ] I have read the CONTRIBUTING document.
- [ X] My code follows the code style of this project. See CODING.md.
- [ X] I have updated the documentation accordingly. (doesn't apply)
- [ X] I have added tests to cover my changes, and all previous tests pass. (doesn't apply)

### CODE REVIEW

**Comment by Aang23** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by michaelld** [comment]
Thanks for reporting this issue here. We actually found it during testing after the 4.1.0.0 release & there is a fix in our internal pipeline already. Leaving this PR open until our internal one is merged.

**Comment by Aang23** [comment]
You're welcome!
Though, it seems like this issue has been around for quite a long time, while trying to get this setup working only versions from a few years ago worked as expected.

**Comment by michaelld** [comment]
Yes it looks like the commit causing this issue was merged Feb 10, 2017 ... clearly we don't have a lot of DBSRX users out there!

**Comment by mbr0wn** [comment]
@Aang23 many many thanks for this PR. Like @michaelld said, we had already fixed it (but it takes some time to get internal reviews etc.). Our fix looks a lot like yours and will be pushed public very soon. I'll close this, but again, thanks for the fix and the attention.

**Pull request closed without merging**
