### PR TITLE
Fixes to address GCC warnings, especially from newer compiler versions.

### PR DESCRIPTION
**Pull request by kb1vc**
# Pull Request Details
The newer GCC compilers complain about a lot of "features" in the uhd code.  Not all of these are *wrong* but the extensive babble of warnings is likely to obscure something important someday. 

The changes here were made to tag v3.14.1.1

## Description
Most changes relate to syntactical issues -- case blocks that fall-through (the compiler frets over this perhaps hoping to prevent the next "goto fail" bug.) or unused functions or parameters. 

Some changes address an inherent "bad practice" quieting the warning, by re-expressing the operation. (For instance "memcpy(complex_thingie_ptr, other_complex_thingie_ptr, sizeof(other_complex_thingie))" is somewhat problematic and scary as heck, but it is embedded in code that was written while dinosaurs roamed the earth.  The warning is quieted by coercing the two pointers to (void*).  Note that the code is marked "FIXME.")

LibUSB deprecated the set_debug call.  As the CMake scripts don't appear to specify a minimum libusb version (do they?) the code in libusb1_base.cpp conditions the call based on the API version.
Perhaps this should be wrapped in a macro? 

The commit message for fda817411176e7164958ddb494bfc718c4f69f7c lists the changes to each file, and their rationale, in detail. 

## Related Issue

No apparent related issues?

## Which devices/areas does this affect?

These changes should not change *any* behavior, but extend across code that is used by all devices. 

## Testing Done
This code has been tested against gcc 9.2.1, but only in the sense that it compiles cleanly, and works with a uhd based application.  What test regime *should* requesters implement? I've run "make test" and all tests pass. 

## Checklist

- [ x] I have read the CONTRIBUTING document.
- [ x] My code follows the code style of this project. See CODING.md.
- [ x] I have updated the documentation accordingly.
- [ x] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

**Comment by natetemple** [comment]
hi @kb1vc 

Can you please rebase this PR off of the current master branch, so it does not include all these outdated commits?

**Comment by kb1vc** [comment]
Yes I will.  I didn't realize what a dumpster fire I'd submitted.  Sorry.

**Comment by natetemple** [comment]
@kb1vc actually, can you rebase this off of the 3.15 LTS branch: https://github.com/EttusResearch/uhd/tree/UHD-3.15.LTS 

Master is has a large delta vs the 3.15 branch as we are preparing to release UHD 4.0 soon.

**Comment by kb1vc** [comment]
I'm going to close this pull request and propose a new one.  

Many of these fixes have since been implemented by others.  Only a few fixes remain.

**Pull request closed without merging**
